package com.monilitocastro.practicecar.statepattern;

public enum DriversActionType {
	TURN_IGNITION_ON,
	TURN_IGNITION_OFF,
	DEPRESS_ACCELERATOR_PEDAL,
	DEPRESS_BRAKE_PEDAL,
	DEPRESS_CLUTCH_PEDAL,
	TURN_WHEEL_LEFT,
	TURN_WHEEL_RIGHT,
	SHIFT_UP,
	SHIFT_DOWN,
	DRIVING,
	READY_TO_DRIVE,
	NOT_DRIVING,
	SMILE,
	LAUGH
}
